const defaults={count:0,goal:100,tasks:[{name:'宿題をする',points:5,color:'green'},{name:'読書をする（30分）',points:3,color:'blue'},{name:'お手伝いをする',points:5,color:'yellow'},{name:'運動をする',points:5,color:'red'},{name:'早く寝る（21時までに）',points:3,color:'green'}]};
let state=JSON.parse(localStorage.getItem('marbleCollection')||'null')||structuredClone(defaults); let editing=-1;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('marbleCollection',JSON.stringify(state))}
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='home')renderHome();if(id==='tasks')renderTasks();if(id==='settings')renderSettings();scrollTo(0,0)}
function renderHome(){let pct=Math.min(100,state.count/state.goal*100);$('#count').textContent=state.count;$('#goalText').textContent=state.goal;$('#remaining').textContent=Math.max(0,state.goal-state.count);$('#bar').style.width=pct+'%';let box=$('#marbles');box.innerHTML='';let total=Math.min(50,Math.ceil(state.count/state.goal*50));for(let i=0;i<total;i++){let m=document.createElement('i');m.className='marble '+state.tasks[i%state.tasks.length]?.color;box.append(m)}}
function renderTasks(){let list=$('#taskList');list.innerHTML='';state.tasks.forEach((t,i)=>{let row=document.createElement('article');row.className='task';row.innerHTML=`<i class="mini ${t.color}"></i><strong>${esc(t.name)}</strong><span class="points">${t.points} 個</span><button class="done">達成！</button>`;row.querySelector('button').onclick=()=>achieve(i);list.append(row)})}
function achieve(i){state.count+=state.tasks[i].points;save();toast(`${state.tasks[i].points}個のビー玉をゲット！`);if(state.count>=state.goal){setTimeout(()=>{$('#completeGoal').textContent=state.goal;go('complete')},450)}else renderTasks()}
function renderSettings(){let list=$('#settingList');list.innerHTML='';state.tasks.forEach((t,i)=>{let row=document.createElement('div');row.className='setting-row';row.innerHTML=`<input aria-label="項目名" value="${attr(t.name)}"><input aria-label="ビー玉数" type="number" min="1" max="100" value="${t.points}"><select aria-label="色"><option value="green">みどり</option><option value="blue">あお</option><option value="yellow">きいろ</option><option value="red">あか</option></select><button class="delete">削除</button>`;row.querySelector('select').value=t.color;row.querySelector('.delete').onclick=()=>{state.tasks.splice(i,1);renderSettings()};list.append(row)});$('#goal').value=state.goal}
function collectSettings(){let rows=[...$$('.setting-row')];state.tasks=rows.map(r=>({name:r.querySelector('input').value.trim()||'名前なし',points:Math.max(1,+r.querySelectorAll('input')[1].value||1),color:r.querySelector('select').value}));state.goal=Math.max(1,+$('#goal').value||100);if(state.count>=state.goal)state.count=state.goal;save();toast('設定を保存しました');go('home')}
function openDialog(){editing=-1;$('#taskForm').reset();$('#taskPoints').value=5;$('#taskDialog').showModal()}
$('#taskForm').addEventListener('submit',e=>{e.preventDefault();state.tasks.push({name:$('#taskName').value.trim(),points:+$('#taskPoints').value,color:$('#taskColor').value});save();$('#taskDialog').close();renderTasks();toast('項目を追加しました')});
function toast(s){let t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function attr(s){return esc(s).replace(/"/g,'&quot;')}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#quickAdd').onclick=openDialog;$('#addTask').onclick=()=>{state.tasks.push({name:'新しい項目',points:1,color:'blue'});renderSettings()};$('#saveSettings').onclick=collectSettings;$('#restart').onclick=()=>{state.count=1;save();go('home');toast('新しいコレクションを1個からスタート！')};renderHome();